### ISSUE TITLE
Thumbor metrics not visible

### ISSUE THREAD

**Issue by sktoiva** [thumbor-community/prometheus#14] opened 2022-11-14 19:42 UTC
I'm running Thumbor 7.3 with `tc_prometheus` 2.0 with the default configuration:

```
# thumbor.conf
METRICS = 'tc_prometheus.metrics.prometheus_metrics'

# optional with defaults
PROMETHEUS_SCRAPE_PORT = 8000 
```

I'm getting Prometheus metrics in the port 8000.

However, the only metrics that are published are `python_*` and `process_*` metrics. The Thumbor metrics are missing. Any idea on how to enable them or debug things further?

Below is the full output from the metrics port:

```
# HELP python_gc_objects_collected_total Objects collected during gc
# TYPE python_gc_objects_collected_total counter
python_gc_objects_collected_total{generation="0"} 583.0
python_gc_objects_collected_total{generation="1"} 336.0
python_gc_objects_collected_total{generation="2"} 7.0
# HELP python_gc_objects_uncollectable_total Uncollectable object found during GC
# TYPE python_gc_objects_uncollectable_total counter
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0
python_gc_objects_uncollectable_total{generation="2"} 0.0
# HELP python_gc_collections_total Number of times this generation was collected
# TYPE python_gc_collections_total counter
python_gc_collections_total{generation="0"} 131.0
python_gc_collections_total{generation="1"} 11.0
python_gc_collections_total{generation="2"} 1.0
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="10",patchlevel="8",version="3.10.8"} 1.0
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 0.0
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 0.0
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.668414974e+09
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 0.0
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 8.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1.048576e+06
```

**Comment by sktoiva** [comment] 2022-11-14 20:04
And as an additional note, if I switch the `METRICS` config to `thumbor.metrics.logger_metrics`, the metrics are visible in the logs:

```
...
thumbor:DEBUG METRICS: timing: response.time:66
thumbor:DEBUG METRICS: timing: response.time.304:66
thumbor:DEBUG METRICS: inc: response.status.304:1
thumbor:DEBUG METRICS: inc: response.format.png:1
thumbor:DEBUG METRICS: timing: response.time.png:66
thumbor:DEBUG METRICS: inc: response.bytes.png:15365
thumbor:DEBUG METRICS: inc: response.count:1
...
```

**Comment by richard5mith** [comment] 2023-06-18 14:55
I have this problem too. Whether installing from pip or github directly, nothing comes out.

**Comment by savar** [comment] 2023-07-19 06:33
Hi, sorry for the very late reply. I am trying to reproduce that but failed to be honest.

What I did:
```bash
docker run --rm -ti python:3.10 bash
```

In this docker container I basically did:
```bash
apt update -qqq; apt install tmux vim -y
tmux
# tiling into two windows
# CTRL+b + "
### window 1
pip install thumbor # installed thumbor 7.5.2
pip install tc_prometheus
pip list
# ... snip ...
prometheus-client    0.17.1
statsd               3.3.0
tc-prometheus        2.0.0
thumbor              7.5.2
thumbor-plugins-gifv 0.1.2
tornado              6.3.2
# ... snip ...
cp /usr/local/lib/python3.10/site-packages/thumbor/thumbor.conf /tmp/
vim /tmp/thumbor.conf
# in this vim I added the `METRICS=..` line so that it looked like:
tail -n 2 /tmp/thumbor.conf
METRICS = 'tc_prometheus.metrics.prometheus_metrics'

# starting thumbor
thumbor -c /tmp/thumbor.conf

### Window 2
# as soon as the above was done I did:
curl localhost:8000
# which indeed only had the process metrics but then I tried to query thumbor on
curl localhost:8888
# and on
curl localhost:8888/unsafe/https://www.shutterstock.com/image-vector/set-colorful-flowers-beautiful-floral-600w-288457640.jpg -o /tmp/pic.jpg
# and afterwards doing
curl localhost:8000
# gave the following output (shortened)
# ... snip ...
# TYPE thumbor_response_status_incr_created gauge
thumbor_response_status_incr_created{statuscode="400"} 1.6897483181353676e+09
thumbor_response_status_incr_created{statuscode="200"} 1.689748320240255e+09
# HELP thumbor_response_none__smart_count_incr_total thumbor_response_none__smart_count_incr
# TYPE thumbor_response_none__smart_count_incr_total counter
thumbor_response_none__smart_count_incr_total 1.0
# HELP thumbor_response_none__smart_count_incr_created thumbor_response_none__smart_count_incr
# TYPE thumbor_response_none__smart_count_incr_created gauge
thumbor_response_none__smart_count_incr_created 1.689748320204941e+09
# HELP thumbor_response_none__smart_latency thumbor_response_none__smart_latency
# TYPE thumbor_response_none__smart_latency summary
thumbor_response_none__smart_latency_count 1.0
thumbor_response_none__smart_latency_sum 1.4120000000000001
# HELP thumbor_response_none__smart_latency_created thumbor_response_none__smart_latency
# TYPE thumbor_response_none__smart_latency_created gauge
thumbor_response_none__smart_latency_created 1.6897483202050543e+09
# HELP thumbor_storage_hit_incr_total thumbor_storage_hit_incr
# TYPE thumbor_storage_hit_incr_total counter
thumbor_storage_hit_incr_total 1.0
# HELP thumbor_storage_hit_incr_created thumbor_storage_hit_incr
# TYPE thumbor_storage_hit_incr_created gauge
thumbor_storage_hit_incr_created 1.6897483202057383e+09
# HELP thumbor_response_not__smart_count_incr_total thumbor_response_not__smart_count_incr
# TYPE thumbor_response_not__smart_count_incr_total counter
thumbor_response_not__smart_count_incr_total 1.0
# HELP thumbor_response_not__smart_count_incr_created thumbor_response_not__smart_count_incr
# TYPE thumbor_response_not__smart_count_incr_created gauge
thumbor_response_not__smart_count_incr_created 1.6897483202402904e+09
# HELP thumbor_response_not__smart_latency thumbor_response_not__smart_latency
# TYPE thumbor_response_not__smart_latency summary
thumbor_response_not__smart_latency_count 1.0
thumbor_response_not__smart_latency_sum 36.632999999999996
# HELP thumbor_response_not__smart_latency_created thumbor_response_not__smart_latency
# TYPE thumbor_response_not__smart_latency_created gauge
thumbor_response_not__smart_latency_created 1.689748320240355e+09
# HELP thumbor_response_format_incr_total thumbor_response_format_incr
# TYPE thumbor_response_format_incr_total counter
thumbor_response_format_incr_total{extension="jpg"} 1.0
# HELP thumbor_response_format_incr_created thumbor_response_format_incr
# TYPE thumbor_response_format_incr_created gauge
thumbor_response_format_incr_created{extension="jpg"} 1.6897483202404642e+09
# HELP thumbor_response_bytes_incr_total thumbor_response_bytes_incr
# TYPE thumbor_response_bytes_incr_total counter
thumbor_response_bytes_incr_total{extension="jpg"} 37417.0
# HELP thumbor_response_bytes_incr_created thumbor_response_bytes_incr
# TYPE thumbor_response_bytes_incr_created gauge
thumbor_response_bytes_incr_created{extension="jpg"} 1.6897483202405527e+09
# ... snip ...
```

so in case you still have that issue, please tell me exactly how I can get to that point.

**Comment by richard5mith** [comment] 2023-08-13 18:16
Just looking at this again and it does now appear to be working, and that's on a server that I haven't touched since June 18th when I reported this. It hasn't been restarted, nor has the config changed. So I'm not quite sure why now I seem to have the data I didn't have before...

**Comment by savar** [comment] 2023-09-12 06:41
Just a wild guess: you might have not yet queried for an image when you tested it. Most metrics are only registered when they are "triggered" the first time you ask for an image as an example.

I will close this for now. Feel free to re-open if you have the issue again and have a way to reproduce it.

**Closed by savar** 2023-09-12 06:41 UTC

**Comment by ingram90** [comment] 2023-09-28 02:22
We have experienced the same issue, and it could not be reproduced in our local Docker test environment. 

However, after deploying to Kubernetes (AWS EKS), it seems that the specific metrics for Thumbor are not visible. 

It's possible that the tc_metrics may require additional permissions that are not available in a sandbox environment like Kubernetes ?

**Comment by savar** [comment] 2023-10-03 11:41
Not really.. we had it running in a kubernetes cluster (not EKS but within AWS back then) and there was no issue. But without more information I cannot tell what the issue might be.
